# Generated by Django 4.2.5 on 2023-10-04 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=20)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
