# Generated by Django 4.2.5 on 2023-10-04 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installments', models.PositiveSmallIntegerField()),
                ('installments_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='rate_table.ratetable')),
            ],
            options={
                'ordering': ['installment_value'],
            },
        ),
    ]
