# Generated by Django 4.2.5 on 2023-10-04 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installmentInterest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installmentInterestValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comissionValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installmentValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cardNumber', models.CharField(max_length=20)),
                ('desiredValue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('totalLoan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['totalLoan'],
            },
        ),
    ]
