# Generated by Django 4.2.5 on 2023-10-04 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_table', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_interest_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comission_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_number', models.CharField(max_length=20)),
                ('desired_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_loan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('rate_table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rate_table.ratetable')),
            ],
            options={
                'ordering': ['total_loan'],
            },
        ),
    ]
