# Generated by Django 3.2.22 on 2023-10-07 23:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate_table', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installments', models.PositiveSmallIntegerField()),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_to_get', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_to_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modality', models.CharField(choices=[('Cartão de Crédito', 'Cc'), ('Crédito Consignado', 'Ccon')], max_length=20)),
                ('stream', models.CharField(choices=[('Automático', 'Auto'), ('Manual', 'Manual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('rate_table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rate_table.ratetable')),
            ],
            options={
                'ordering': ['loan_to_get'],
            },
        ),
    ]
