# Generated by Django 4.2.5 on 2023-10-04 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('account_type_label', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
